bindsym $mod+o mode "Application and Wallpaper Launcher"

mode "Application and Wallpaper Launcher" {
	bindsym $mod+l exec swaylock

	# Apps
	bindsym e exec emacs
	bindsym t exec telegram-desktop
	bindsym o exec obs
	bindsym g exec gimp
	bindsym p exec pavucontrol
	bindsym h exec $term -e htop
	bindsym z exec zathura
	bindsym f exec firefox

	# Wallpaper
	bindsym w output * bg $HOME/Pictures/wallpaper.jpg fill
	bindsym 1 output * bg $HOME/Pictures/wallpaper1.jpg fill
	bindsym 2 output * bg $HOME/Pictures/wallpaper2.jpg fill
	bindsym 3 output * bg $HOME/Pictures/wallpaper3.jpg fill
	bindsym 4 output * bg $HOME/Pictures/wallpaper4.jpg fill
	bindsym 5 output * bg $HOME/Pictures/wallpaper5.jpg fill
	bindsym 6 output * bg $HOME/Pictures/wallpaper6.jpg fill
	bindsym 7 output * bg $HOME/Pictures/wallpaper7.jpg fill
	bindsym 8 output * bg $HOME/Pictures/wallpaper8.jpg fill
	bindsym 9 output * bg $HOME/Pictures/wallpaper9.jpg fill
	bindsym 0 output * bg $HOME/Pictures/wallpaper10.jpg fill
	bindsym minus output * bg /usr/share/backgrounds/sway/Sway_Wallpaper_Blue_1920x1080.png fill

	bindsym Escape mode "default"
	bindsym Return mode "default"
}
