bindsym $mod+o mode "Application Launcher"

mode "Application Launcher" {
	bindsym $mod+l exec swaylock

	# Apps
	bindsym o exec obs
	bindsym g exec gimp
	bindsym l exec libreoffice
	bindsym p exec pavucontrol
	bindsym h exec $term -e htop
	bindsym f exec firefox
	bindsym z exec zathura

	bindsym Escape mode "default"
	bindsym Return mode "default"
}
