bindsym $mod+o mode "Application Launcher"

mode "Application Launcher" {
	bindsym $mod+l exec swaylock

	# Apps
	bindsym t exec telegram-desktop
	bindsym o exec obs
	bindsym g exec gimp
	bindsym p exec pavucontrol
	bindsym h exec $term -e htop
	bindsym f exec firefox

	bindsym Escape mode "default"
	bindsym Return mode "default"
}
