mode "power mode: [s]hutdown, [r]eboot" {
	bindsym s exec rm $HOME/.bash_history && poweroff
	bindsym r exec rm $HOME/.bash_history && reboot

	bindsym Return mode "default"
	bindsym Escape mode "default"
}

bindsym $mod+p mode "power mode: [s]hutdown, [r]eboot" 
