font_family      family="CommitMono Nerd Font"
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size 14.0

enable_audio_bell no

notify_on_cmd_finish unfocused

confirm_os_window_close 0

input_delay 0
repaint_delay 2
sync_to_monitor no
wayland_enable_ime no

include ./theme.conf
#foreground #ffffff
#background #2d3132
#cursor #00f7ff

shell_integration no-cursor
cursor_shape block
cursor_stop_blinking_after 0
