unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

set -g set-clipboard on
set-window-option -g mode-keys vi
set -g mouse on

set -g status-left-length 50
set -g status-right-length 70

set -g status-right "%H:%M:%S %A %d-%m-%Y"
set -g status-bg darkgreen
set -g status-fg white
set-window-option -g window-status-current-style fg=orange

set -g display-panes-time 2500
set-option -s status-interval 5

set-option -sg escape-time 1

set -g default-terminal 'xterm-256color'

set -g history-limit 10000

set -g base-index 1
setw -g pane-base-index 1
