[main]
font=Terminus:size=10

[bell]
system=no

[cursor]
style=block
blink=yes
blink-rate=500

[mouse]
hide-when-typing=yes

#eltonzip theme:
[colors]
foreground=ffffff
background=292c30

regular0=1e1e1e
regular1=ed1515
regular2=11d116
regular3=fdd300
regular4=6cacff
regular5=ff6923
regular6=00ffff
regular7=ffffff

bright0=5e5e5e
bright1=ed1515
bright2=11d116
bright3=fffb29
bright4=5fd7ff
bright5=0ff000
bright6=c78fff
bright7=ffffff
