assign [class="Emacs"] 3
assign [class="firefox"] 10
assign [class="Chromium"] 10
assign [class="Pavucontrol"] 9
assign [class="libreoffice-startcenter"] 8
assign [class="libreoffice"] 8
assign [class="Gimp"] 7
assign [class="gimp"] 7
assign [class="obs"] 6
assign [class="Zathura"] 4
