bindsym $mod+o mode "Application and Wallpaper Launcher"

mode "Application and Wallpaper Launcher" {
	bindsym $mod+l exec i3lock

	# Apps
	bindsym e exec emacs
	bindsym l exec librewolf
	bindsym o exec obs
	bindsym g exec gimp
	bindsym p exec pavucontrol
	bindsym h exec i3-sensible-terminal -e htop
	bindsym z exec zathura
	bindsym c exec chromium

	# Wallpaper
	bindsym w exec feh --bg-scale $HOME/Pictures/wallpaper.jpg
	bindsym 1 exec feh --bg-scale $HOME/Pictures/wallpaper1.jpg
	bindsym 2 exec feh --bg-scale $HOME/Pictures/wallpaper2.jpg
	bindsym 3 exec feh --bg-scale $HOME/Pictures/wallpaper3.jpg
	bindsym 4 exec feh --bg-scale $HOME/Pictures/wallpaper4.jpg
	bindsym 5 exec feh --bg-scale $HOME/Pictures/wallpaper5.jpg
	bindsym 6 exec feh --bg-scale $HOME/Pictures/wallpaper6.jpg
	bindsym 7 exec feh --bg-scale $HOME/Pictures/wallpaper7.jpg
	bindsym 8 exec feh --bg-scale $HOME/Pictures/wallpaper8.jpg
	bindsym 9 exec feh --bg-scale $HOME/Pictures/wallpaper9.jpg
	bindsym 0 exec feh --bg-scale $HOME/Pictures/wallpaper10.jpg
	bindsym minus exec xsetroot -solid black

	bindsym Escape mode "default"
	bindsym Return mode "default"
}
