unbind C-b
set -g prefix C-Space
bind C-Space send-prefix
setw -g mouse on
set-window-option -g mode-keys vi

bind s split-window -v
bind v split-window -h

bind C-h select-pane -L
bind C-j select-pane -D
bind C-k select-pane -U
bind C-l select-pane -R

set -g status-right ""
set -g status-bg "color4"
set -g status-fg "color7"
